#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 孙耀珠的博客
description:
domain: yzyzsun.me

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/avatar.jpg

#
# Flags below are optional
#

excerpt_separator: "<!--more-->"

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: yzyzsun@gmail.com
  facebook:
  flickr:
  github: yzyzsun
  instagram:
  linkedin: yzyzsun
  pinterest:
  rss: true
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: yzyzsun

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-65994616-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://blog.yzyzsun.me

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: highlight

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

feed:
  path: feed-atom.xml

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
